function f123() {
    console.log(1);
    console.log(2);
    console.log(3);
}
f123();
console.log('A');
console.log('Z');
console.log('B');
f123();
console.log('F');
console.log('C');
console.log('P');
console.log('J');
console.log('U');
f123();
console.log('A');
console.log('Z');
console.log('J');
console.log('I');
