/**
 * Guide List Info
 */
var infoPcardFolder = "../pages/";
var infoPcardList = [
    //label : hidden, modify, add, end, gui, ing, chk, chk02
    {
        label: "end",
        auth: "SK, SB, US, UA, UP, MA, 공통",
        dep1: "메인",
        dep2: "메인",
        dep3: "",
        url: "main/main.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK, SB, US, UA, UP, MA, 공통",
        dep1: "사이트관리",
        dep2: "",
        dep3: "",
        url: "a2.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "사이트관리",
        dep2: "사이트 등록요청",
        dep3: "사이트 목록",
        url: "PBA010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "사이트관리",
        dep2: "사이트 일시정지",
        dep3: "일시정지 목록",
        url: "PBA010200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "사이트관리",
        dep2: "담당자정보(팝업)관리",
        dep3: "담당자 목록",
        url: "PBA010300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "사이트관리",
        dep2: "공지사항",
        dep3: "공지사항 목록",
        url: "PCA100200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "사이트관리",
        dep2: "예산현황조회",
        dep3: "",
        url: "PBA010500C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "tab_신규요청",
        url: "PBA020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "tab_정보변경요청",
        url: "PBA020103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "tab_Host정보 불일치 수정요청",
        url: "PBA020106C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드신청정보조회/처리",
        dep3: "카드신청정보조회",
        url: "PBA020200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드신청정보조회/처리",
        dep3: "신규등록",
        url: "PBA020201C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드신청정보조회/처리",
        dep3: "신규등록 처리 완료",
        url: "PBA020203C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드해지정보조회/처리",
        dep3: "카드해지정보조회",
        url: "PBA020600C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드해지정보조회/처리",
        dep3: "카드해지/거절",
        url: "PBA020601C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "카드해지정보조회/처리",
        dep3: "카드해지/거절 완료",
        url: "PBA020600C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "한도증액정보조회/처리",
        dep3: "한도증액정보조회",
        url: "PBA020300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "한도증액정보조회/처리",
        dep3: "한도변경 처리/거절",
        url: "PBA020301C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "한도증액정보조회/처리",
        dep3: "한도변경 처리/거절 완료",
        url: "PBA020302C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "관리자조회/등록",
        dep3: "관리자 목록",
        url: "PBA020400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "tab_공급사등록",
        url: "PBA020500C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "tab_공급사정보변경",
        url: "PBA020501C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "tab_카드신규발급",
        url: "PBA020503C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "tab_카드해지",
        url: "PBA020504C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "tab_한도변경",
        url: "PBA020506C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "승인/매입관리",
        dep2: "승인/매입관리",
        dep3: "승인/매입내역 목록",
        url: "PBA030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "승인/매입관리",
        dep2: "거래에러조회",
        dep3: "",
        url: "approval02.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "승인/매입관리",
        dep2: "취소/환급내역조회",
        dep3: "목록",
        url: "PBA030300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "승인/매입관리",
        dep2: "취소/환급내역조회",
        dep3: "취소/환급내역 상세",
        url: "PBA030301C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "법인관리자관리",
        dep3: "목록",
        url: "PBA040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "법인관리자관리",
        dep3: "등록",
        url: "keb02.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "법인관리자관리",
        dep3: "상세(변경/삭제)",
        url: "keb03.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "지점관리자관리",
        dep3: "목록",
        url: "PBA040200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "지점관리자관리",
        dep3: "등록",
        url: "keb05.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "KEB관리자관리",
        dep2: "지점관리자관리",
        dep3: "상세(변경/삭제)",
        url: "keb06.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "통계자료",
        dep2: "월별 전체 사용실적",
        dep3: "목록",
        url: "PBA050100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "통계자료",
        dep2: "월별 전체 사용실적",
        dep3: "상세",
        url: "PBA050101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "통계자료",
        dep2: "연별 전체 사용실적",
        dep3: "목록",
        url: "PBA050200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "통계자료",
        dep2: "연별 전체 사용실적",
        dep3: "상세",
        url: "PBA050200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 조회",
        url: "PAP040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 변경완료",
        url: "PAP040101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 비밀번호 입력",
        url: "PAP040104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 완료",
        url: "PAP040105C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "시스템관리",
        dep2: "예산관리(배치)",
        dep3: "",
        url: "PBA070100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "시스템관리",
        dep2: "사이트관리/등록",
        dep3: "사이트조회",
        url: "PBA070600C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "시스템관리",
        dep2: "사이트관리/등록",
        dep3: "사이트 등록",
        url: "PBA070601C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "ERP연동관리",
        dep2: "ERP스케줄러(배치)",
        dep3: "",
        url: "PBA070200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "ERP연동관리",
        dep2: "출하정보",
        dep3: "출하정보조회",
        url: "PBA070300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "ERP연동관리",
        dep2: "출하정보",
        dep3: "출하정보신규등록",
        url: "PBA070302C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SK",
        dep1: "ERP연동관리",
        dep2: "공급사정보",
        dep3: "",
        url: "PBA070400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "승인/매입관리",
        dep2: "승인내역조회/처리",
        dep3: "",
        url: "PBR010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "승인/매입관리",
        dep2: "매입/환급처리조회",
        dep3: "",
        url: "PBR010200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "승인/매입관리",
        dep2: "취소/환급내역조회",
        dep3: "",
        url: "PBR010300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "신규요청",
        url: "PBR030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "정보변경요청",
        url: "PBR030103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "요청업무관리",
        dep2: "공급사정보처리",
        dep3: "Host정보 불일치 수정요청",
        url: "PBR030106C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "공급사등록",
        url: "PBR030200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "요청업무관리",
        dep2: "요청업무처리내역",
        dep3: "공급사정보변경",
        url: "PBR030210C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "",
        url: "PBR020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "SB",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "",
        url: "PAP040104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "메인",
        dep2: "",
        dep3: "",
        url: "main02.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "구매승인관리",
        dep2: "결재요청내역/처리",
        dep3: "결재요청 목록",
        url: "PAP010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "구매승인관리",
        dep2: "결재완료내역조회",
        dep3: "결재완료 목록",
        url: "PAP010400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "구매승인관리",
        dep2: "반려내역조회",
        dep3: "반려내역 목록",
        url: "PAP010300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "통계자료",
        dep2: "부서사용실적",
        dep3: "",
        url: "PAP020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "",
        url: "PAP030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 조회",
        url: "PAP040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 변경완료",
        url: "PAP040101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 비밀번호 입력",
        url: "PAP040104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "US",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 완료",
        url: "PAP040105C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "메인",
        dep2: "",
        dep3: "",
        url: "main03.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "처리현황관리",
        dep2: "전체처리현황조회",
        dep3: "목록",
        url: "PCA010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "처리현황관리",
        dep2: "전체처리현황조회",
        dep3: "상세",
        url: "PCA010101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "처리현황관리",
        dep2: "사이트일시정지",
        dep3: "일시정지 목록",
        url: "PCA010200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "처리현황관리",
        dep2: "미결재현황조회/처리",
        dep3: "목록",
        url: "PCA010300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "부서/예산관리",
        dep2: "예산전체조회",
        dep3: "",
        url: "PCA020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "부서/예산관리",
        dep2: "부서/예산관리",
        dep3: "목록",
        url: "PCA020200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "부서/예산관리",
        dep2: "부서/예산관리",
        dep3: "부서신규등록",
        url: "PCA020201C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "부서/예산관리",
        dep2: "부서이동",
        dep3: "부서이동(부서단위이동)",
        url: "PCA020300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "부서/예산관리",
        dep2: "부서이동",
        dep3: "부서이동(사용자 이동)",
        url: "PCA020400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "공급사관리",
        dep3: "공급사 목록",
        url: "PCA030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "공급사관리",
        dep3: "공급사 등록",
        url: "PCA030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "PCARD사용자관리",
        dep3: "사용자 목록",
        url: "PCA030200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "결재자관리",
        dep3: "결재자 목록",
        url: "PCA030300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "결재단계관리",
        dep3: "결재자 목록",
        url: "PCA030400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "사용자관리",
        dep2: "부재관리",
        dep3: "부재관리 목록",
        url: "PCA030500C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },

    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "총발급내역조회",
        dep3: "",
        url: "PCA040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "신규카드요청/처리",
        dep3: "카드요청 목록",
        url: "PCA040200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "카드해지",
        dep3: "카드해지요청 목록",
        url: "PCA040300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "한도조회",
        dep3: "",
        url: "PCA040400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "한도조회",
        dep3: "pop_카드 정보 조회",
        url: "PCA040301C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "카드관리",
        dep2: "한도증액요청",
        dep3: "요청 목록",
        url: "PCA040500C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "월별예산사용실적",
        dep3: "",
        url: "PCA050200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "공급사별사용실적",
        dep3: "실적 목록",
        url: "PCA050300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "PCARD사용자별 사용실적",
        dep3: "실적 목록",
        url: "PCA050400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "부서별 사용실적",
        dep3: "실적 목록",
        url: "PCA050500C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "월별 전체사용실적",
        dep3: "",
        url: "PCA050700C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "통계자료",
        dep2: "월별 전체사용실적(상세)",
        dep3: "",
        url: "PCA050701C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 조회",
        url: "PAP040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 변경완료",
        url: "PAP040101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 비밀번호 입력",
        url: "PAP040104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UA",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 완료",
        url: "PAP040105C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "메인",
        dep2: "",
        dep3: "",
        url: "main04.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "구매요청내역/처리",
        dep3: "요청/처리 내역 목록",
        url: "PCU010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "구매요청내역/처리",
        dep3: "요청/처리 내역 상세",
        url: "PCU010101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "결재완료내역조회",
        dep3: "결재완료내역 목록",
        url: "PCU010400C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "결재완료내역조회",
        dep3: "결재완료내역 상세",
        url: "PCU010401C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "반려내역조회",
        dep3: "반려내역 목록",
        url: "PCU010300C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "구매요청내역/처리",
        dep2: "반려내역조회",
        dep3: "반려내역 상세",
        url: "PCU010301C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "통계자료",
        dep2: "부서사용실적",
        dep3: "",
        url: "PCU020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "통계자료",
        dep2: "부서사용실적",
        dep3: "pop_부서 사용실적 상세",
        url: "PCU020101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "부재내역 목록(등록)",
        url: "PCU030102C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "부재등록완료",
        url: "PCU030103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "부재내역 목록(수정/삭제)",
        url: "PCU030103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "부재수정완료",
        url: "PCU030103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "부재관리",
        dep2: "부재등록/해제",
        dep3: "부재 삭제 완료",
        url: "PCU030103C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 조회",
        url: "PAP040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "개인정보관리",
        dep2: "개인정보조회/변경",
        dep3: "개인정보 변경완료",
        url: "PAP040101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 비밀번호 입력",
        url: "PAP040104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "UP",
        dep1: "개인정보관리",
        dep2: "비밀번호변경",
        dep3: "변경 완료",
        url: "PAP040105C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "메인",
        dep2: "",
        dep3: "",
        url: "main05.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청",
        dep2: "신규요청",
        dep3: "",
        url: "PMC010100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청",
        dep2: "신규요청",
        dep3: "pop_P-Card사용자정보 검색",
        url: "PMC010104C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청",
        dep2: "반려건 재요청",
        dep3: "반려내역 목록",
        url: "PMC010200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청처리조회",
        dep2: "진행/결재내역조회(세금계산서출력)",
        dep3: "",
        url: "PMC020100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청처리조회",
        dep2: "승인/매입취소내역",
        dep3: "승인/매입취소내역 목록",
        url: "PMC020200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "대금요청처리조회",
        dep2: "승인/매입취소내역",
        dep3: "승인/매입취소내역 상세",
        url: "PMC020201C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사실적조회",
        dep2: "매출실적통계",
        dep3: "",
        url: "PMC030100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사실적조회",
        dep2: "대금입금내역조회",
        dep3: "대금입금내역 목록",
        url: "PMC030200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사실적조회",
        dep2: "대금입금내역조회",
        dep3: "대금입금내역 상세",
        url: "PMC030201C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사정보조회/변경",
        dep2: "tab_변경가능항목",
        dep3: "",
        url: "PMC040100C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사정보조회/변경",
        dep2: "tab_변경가능항목",
        dep3: "pop_우편번호 검색",
        url: "info02.html",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사정보조회/변경",
        dep2: "tab_변경요청항목",
        dep3: "",
        url: "PMC040101C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사정보조회/변경",
        dep2: "tab_변경요청리스트",
        dep3: "",
        url: "PMC040102C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "MA",
        dep1: "공급사정보조회/변경",
        dep2: "비밀번호 변경",
        dep3: "",
        url: "PMC040200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "쪽지함",
        dep2: "받은쪽지함",
        dep3: "",
        url: "PAP050301D.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "쪽지함",
        dep2: "보낸쪽지함",
        dep3: "",
        url: "PAP050300D.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "쪽지함",
        dep2: "쪽지보내기",
        dep3: "",
        url: "PAP050302D.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "부가서비스",
        dep2: "공지사항",
        dep3: "",
        url: "PCA100200C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "부가서비스",
        dep2: "Q&A",
        dep3: "",
        url: "PCU050100D.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "ID/비밀번호 찾기",
        dep2: "tab_ID찾기",
        dep3: "",
        url: "PCM020000C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "ID/비밀번호 찾기",
        dep2: "tab_비밀번호찾기",
        dep3: "",
        url: "PCM030000C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "공급사등록",
        dep2: "",
        dep3: "",
        url: "PCM040000C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },
    {
        label: "chk",
        auth: "공통",
        dep1: "PCARD사용자/결재자등록",
        dep2: "",
        dep3: "",
        url: "PCM050000C.web",
        status: "",
        date_complete: "",
        writer: "",
        etc: "",
    },


]