/**
 * Guide List Info
 */

var infoGuideFolder = "./mrkp_pages/";

var infoGuideList = [
    //label : hidden, modify, add, end, gui, ing, chk, chk02
    {
        label: "end",
        dep1: "Guide",
        dep2: "Layout",
        dep3: "",
        url: "g_layout.html",
        status: "",
        date_complete: "22.02.23",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Guide",
        dep2: "Dev",
        dep3: "",
        url: "g_to_dev.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "<span class='red'>Ajax후 Script 처리 Guide</span>",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Common",
        dep3: "",
        url: "g_md_common.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Tab",
        dep3: "",
        url: "g_md_tab.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "From",
        dep3: "",
        url: "g_md_form.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Board",
        dep3: "",
        url: "g_md_board.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Table",
        dep3: "",
        url: "g_md_table.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "List",
        dep3: "",
        url: "g_md_list.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Accordian",
        dep3: "",
        url: "g_md_acco.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Button",
        dep3: "",
        url: "g_md_button.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
    {
        label: "end",
        dep1: "Module",
        dep2: "Contents",
        dep3: "",
        url: "g_md_contents.html",
        status: "",
        date_complete: "22.03.07",
        writer: "류승현",
        etc: "",
    },
]